# Generated by Django 5.2.2 on 2025-06-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.CharField(max_length=500)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('llm', models.CharField(choices=[('groq', 'qwen-qwq-32b'), ('antro', 'claude-opus-4-20250514')], default='groq', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
