# Generated by Django 5.2.2 on 2025-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciones',
            name='dark_mode',
        ),
        migrations.AddField(
            model_name='configuraciones',
            name='conn_str',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='system_prompt',
            field=models.CharField(default='Eres un asistente útil.', max_length=500),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
