# Generated by Django 5.2.2 on 2025-06-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_remove_configuraciones_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones',
            name='conn_str',
            field=models.CharField(default='postgresql://user:pass@ip:port/database', max_length=100),
        ),
    ]
