[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.2",
    "langchain-groq>=0.3.2",
    "langchain-openai>=0.3.19",
    "mcp-use>=1.3.0",
    "streamlit>=1.45.1",
]
